dir_proj <- here::here()
dir_cloud <- here::here("cloud_data_visualization")
dir_data <- fs::path(dir_cloud, "data")
dir_raw <- fs::path(dir_data, "raw")
dir_munge <- here::here("munge")
dir_analysis <- here::here("analysis")
dir_reports <- fs::path(dir_cloud, "reports")
